backend:
  name: github
  repo: benyco-dev/benyco-dev.github.io
  branch: master
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_domain: playful-basbousa-ccd102.netlify.app

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - { label: "Body", name: "body", widget: "markdown" }
